spring:
  datasource:
    url: jdbc:mysql://localhost:5432/mastersdet360
    username: root
    password: root
  flyway:
    locations: classpath:db/master_migrations
    enabled: true
    baseline-on-migrate: true
